config/routes.rb
Rails.application.routes.draw do
  

  resources :pets do
    resources :foods
  end

  root :to => redirect('/pets')
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :pet
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  has_many :foods


  def age
    today = Date.current
    today.day - self.created_at.day
  end


  def eaten_foods
    self.foods.map{|food| food.name }.compact
  end

  def food_score
    calories = []
    self.foods.map do |food|
      calories << food.calories
    end
    calories.sum(&:to_i) * 100 / self.max_weight
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @pet = Pet.find(params[:pet_id])
    @foods = Food.all
  end

  def new
    @pet = Pet.find(params[:pet_id])
    @food = Food.new
  end

  # POST /foods
  # POST /foods.json
  def create
    @pet = Pet.find(params[:pet_id])
    @food = @pet.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @pet, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @pet = Pet.find(params[:pet_id])
    @food = @pet.foods.find(params[:id])

    @food.destroy
    respond_to do |format|
      format.html { redirect_to @pet, notice: 'Food was successfully pooped by your pet.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :calories)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :picture, :max_weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/foods/_form.html.erb
<%= form_for([@pet, @food]) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.number_field :calories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/index.html.erb
<h1>List of foods to poop for <%= @pet.name %></h1>

<table>
  <thead>
    <tr>
      <th>Name of food</th>
      <th>Calories in food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pet.foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.calories %></td>
        <td><%= link_to 'Poop this food', [@pet, food], method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Feed Pet new Food', new_pet_food_path(@pet, @food) %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', pet_path(@pet) %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @food.calories %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @food.pet %>
</p>

<%= link_to 'Edit', edit_pet_food_path(@pet, @food) %> |
<%= link_to 'Back', pet_foods_path(@pet, @food) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railspet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :max_weight %><br>
    <%= f.number_field :max_weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Listing pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Max weight</th>
      <th>Full score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.max_weight %></td>
        <td><%= pet.food_score %>%</td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @pet.picture %>
</p>

<p>
  <strong>Max weight:</strong>
  <%= @pet.max_weight %>
</p>
<p>
  <strong>Pet age:</strong>
  <%= @pet.age %>
</p>


<p>
  <strong>Eaten foods:</strong>
  <%= @pet.eaten_foods %>
</p>


<p>
  <strong>Pet full score:</strong>
  <%= @pet.food_score %>% full
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %> |
<% unless @pet.food_score >= 100 %>
  <%= link_to 'Feed your pet', new_pet_food_path(@pet, @food) %>
<% end %> |
<%= link_to'Poop foods', pet_foods_path(@pet) %>